name: advanced_icon
description: A flutter package that contains a collection of icon decoration tools (i.e. gradient, opacity) and icon transition features with cool animation effects.
version: 0.1.2
homepage: https://github.com/ankitmishradev/advanced-icon
repository: https://github.com/ankitmishradev/advanced-icon

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
